// packages/vue-virtual-scroll/example/src/scrollItem.vue
<template>
    <div class="chat-item">
        <img class="avatar" :src="itemData?.avatar" />
        <div class="bubble">
            <p>{{itemData?.content}}</p>
            <div class="meta">
                <time class="posted-date">{{itemData?.time}}</time>
            </div>
        </div>
    </div>
</template>
<script lang="ts">
import { defineComponent, PropType } from 'vue'
import { Message } from './../mock'

export default defineComponent({
    props: {
        itemData: Object as PropType<Message>
    },
    setup() {
    },
})
</script>

// packages/react-virtual-scroll/example/scrollItem.tsx
import * as React from 'react'
import { Message } from './mock'

const ScrollItem: React.FC<Message> = (props) => {
    return (
        <div className="chat-item">
            <img className="avatar" src={props.avatar} />
            <div className="bubble">
                <p>{props.content}</p>
                <div className="meta">
                    <time className="posted-date">{props.time.toString()}</time>
                </div>
            </div>
        </div>       
    )
}

export default ScrollItem
