// packages/react-virtual-scroll/example/tombstone.tsx
import * as React from 'react'

const Tombstone:React.FC = () => {
    return (
        <div className="chat-item">
            <img className="avatar" width="48" height="48" src={require('./images/unknown.jpg')}/>
            <div className="bubble">
                <p></p>
                <p></p>
            </div>
        </div>       
    )
}

export default Tombstone

// packages/vue-virtual-scroll/example/src/tombstone.vue
<template>
      <img class="avatar" width="48" height="48" src="images/unknown.jpg">
      <div class="bubble">
        <p></p>
        <p></p>
        <p></p>
        <div class="meta">
          <time class="posted-date"></time>
        </div>
      </div>
</template>
<script lang="ts">
import { defineComponent } from 'vue'

export default defineComponent({
    setup() {  
    }
})
</script>
